apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "gweihir-dev.fullname" . }}-postgres-pv
  labels:
    {{- include "gweihir-dev.labels" . | nindent 4 }}
    usedBy: {{ include "gweihir-dev.fullname" . }}-postgres
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: {{ .Values.postgres.env.POSTGRES_STORAGE_DIR }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "gweihir-dev.fullname" . }}-local-storage
  volumeMode: Filesystem