apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gweihir-dev.fullname" . }}-postgres-secret
  labels:
    {{- include "gweihir-dev.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.postgres.env.POSTGRES_DB }}