apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gweihir-dev.fullname" . }}-chainlink-node-secret
  labels:
    {{- include "gweihir-dev.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: postgresql://{{ .Values.postgres.env.CHAINLINK_DB_USER }}:{{ .Values.postgres.env.CHAINLINK_DB_PASSWORD }}@{{ include "gweihir-dev.fullname" . }}-postgres:5432/{{ .Values.postgres.env.CHAINLINK_DB }}?sslmode=disable
  USER_EMAIL: {{ .Values.chainlink.env.CHAINLINK_USER_EMAIL }}
  USER_PASSWORD: {{ .Values.chainlink.env.CHAINLINK_USER_PASSWORD }}
  WALLET_PASS: {{ .Values.chainlink.env.CHAINLINK_WALLET_PASSWORD }}
  ETH_URL: {{ .Values.chainlink.env.CHAINLINK_ETH_URL }}