apiVersion: v1
kind: Service
metadata:
  name: {{ include "gweihir-dev.fullname" . }}-chainlink-node-service
  namespace: chainlink
  labels:
    app: {{ include "gweihir-dev.fullname" . }}-chainlink-node
    {{- include "gweihir-dev.labels" . | nindent 4 }}
spec:
  ports:
   - port: 6688
     targetPort: 6688
  selector:
   app: {{ include "gweihir-dev.fullname" . }}-chainlink-node